apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: events
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        elasticsearch:
          hosts:
            - "http://elasticsearch-master.logging:9200"
          indexFormat: "kube-events-{2006-01-02}"
          
