apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: event-exporter
    kubernetes.io/cluster-service: "true"
    version: v0.3.5
  name: event-exporter-gke
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: event-exporter
  template:
    metadata:
      labels:
        k8s-app: event-exporter
        version: v0.3.5
    spec:
      containers:
      - command:
        - /event-exporter
        - -sink-opts=-stackdriver-resource-model=new -endpoint=https://logging.googleapis.com
        - -prometheus-endpoint=:8080
        image: gke.gcr.io/event-exporter:v0.3.5-gke.0
        name: event-exporter
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
            
      - command:
        - /monitor
        - --stackdriver-prefix=container.googleapis.com/internal/addons
        - --api-override=https://monitoring.googleapis.com/
        - --source=event_exporter:http://localhost:8080?whitelisted=stackdriver_sink_received_entry_count,stackdriver_sink_request_count,stackdriver_sink_successfully_sent_entry_count
        - --pod-id=$(POD_NAME)
        - --namespace-id=$(POD_NAMESPACE)
        - --node-name=$(NODE_NAME)
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: gke.gcr.io/prometheus-to-sd:v0.10.0-gke.0
        name: prometheus-to-sd-exporter
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
      dnsPolicy: ClusterFirst
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccount: event-exporter-sa
      serviceAccountName: event-exporter-sa
      volumes:
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: ssl-certs